apiVersion: v2
appVersion: v9.7
description: A Helm chart for XL Release
name: xl-release
version: 9.7

dependencies:
- name: ingress-nginx
  version: 3.1.0
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: ingress-nginx.install

- name: activemq-artemis
  version: 0.0.2
  repository: "file://./subcharts/activemq-artemis"
  condition: activemq-artemis.install

