apiVersion: v2
appVersion: v9.7
description: A Helm chart for XL Release
name: xl-release
version: 9.7

dependencies:
- name: haproxy-ingress
  version: 0.0.27
  repository: "https://kubernetes-charts-incubator.storage.googleapis.com/"
  condition: haproxy-ingress.install

- name: rabbitmq-ha
  version: 1.47.1
  repository: "https://kubernetes-charts.storage.googleapis.com/"
  condition: rabbitmq-ha.install

