apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xl-release.fullname" . }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "xl-release.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "xl-release.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "vpartington/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: xlr-http
              containerPort: 5516
              protocol: TCP
          volumeMounts:
            - name: xlr-bootstrap
              mountPath: /opt/xl-release/xlr-bootstrap
            - name: xlr-data
              mountPath: /opt/xl-release/xlr-data
          livenessProbe:
            httpGet:
              path: /
              port: xlr-http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /
              port: xlr-http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
          env:
            - name: XLR_DEVELOPMENT_MODE
              value: "{{ .Values.xlrDevelopmentMode }}"
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
