# Default values for xl-release.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
ImageRepository: "xebialabs/xl-release"
ImageTag: "9.6"
ImagePullPolicy: "Always"
# ImagePullSecret: xlRelease

ingress:
  Enabled: true
  annotations:
    # ingress.kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - example.com
  tls:
   - secretName: example-secretsName
     hosts:
       - example.com

AdminPassword:
  # Provide the Credential
xlrLicense:
  # Provide the License

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

UseExistingDB:
  Enabled: false
  # If you want to use existing database, change the the value to "true".
  # Uncomment the following lines and provide the values.
  # XLR_DB_URL:
  # XLR_DB_USER:
  # XLR_DB_PASS:
  # XLR_REPORT_DB_URL:
  # XLR_REPORT_DB_USER:
  # XLR_REPORT_DB_PASS:

HealthProbes: true
HealthProbesLivenessTimeout: 60
HealthProbesReadinessTimeout: 60
HealthProbeFailureThreshold: 12
HealthPeriodScans: 10

nodeSelector: {}

tolerations: []

affinity: {}

Persistence:
  Enabled: true
  ## Choose storage class provided by your cloud provider, example "ssd" on GKE, AWS and OpenStack
  StorageClass: "-"
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 10Gi
