{{- if eq .Values.K8sSetup.Platform "Openshift"}}
{{- if not .Values.UseExistingDB.Enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "xl-release.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
---
allowHostNetwork: false
allowHostPID: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
apiVersion: security.openshift.io/v1
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  name: {{ .Release.Name }}-privileged
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ template "xl-release.fullname" . }}-sa
volumes:
- '*'
{{- end }}
{{- end}}

