apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xl-release.fullname" . }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.AdminPassword }}
  release-password:  {{ .Values.AdminPassword | b64enc | quote }}
  {{ else }}
  release-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
