apiVersion: v1
kind: Service
metadata:
  name: {{ template "xl-release.fullname" . }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: xlr-http
      protocol: TCP
      name: xlr-http-svc
  selector:
    app: {{ template "xl-release.name" . }}
    release: {{ .Release.Name }}
