{{$XLR_ADMIN_PASS := .Values.AdminPassword | default "admin"}}
{{$XLR_DB_USER := .Values.UseExistingDB.XLR_DB_USER | default "xlr"}}
{{$XLR_DB_PASS := .Values.UseExistingDB.XLR_DB_PASS | default "xlr"}}
{{$XLR_REPORT_DB_USER := .Values.UseExistingDB.XLR_REPORT_DB_USER | default "xlr-report"}}
{{$XLR_REPORT_DB_PASS := .Values.UseExistingDB.XLR_REPORT_DB_PASS | default "xlr-report"}}
{{$ENABLE_EMBEDDED_QUEUE := .Values.MessageQueue.ENABLE_EMBEDDED_QUEUE | default "false"}}
{{$XLR_TASK_QUEUE_USERNAME := .Values.MessageQueue.XLR_TASK_QUEUE_USERNAME | default "admin"}}
{{$XLR_TASK_QUEUE_PASSWORD := .Values.MessageQueue.XLR_TASK_QUEUE_PASSWORD | default "admin"}}
{{$XLR_TASK_QUEUE_URL := .Values.MessageQueue.XLR_TASK_QUEUE_URL | default "amqp://127.0.0.1:61616"}}
{{$XLR_TASK_QUEUE_NAME := .Values.MessageQueue.XLR_TASK_QUEUE_NAME | default "xlr-tasks-queue"}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "xl-release.fullname" . }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "xl-release.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "xl-release.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "xl-release.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if not .Values.UseExistingDB.Enabled }}
      initContainers:
        - name: wait-for-db
          image: xebialabs/tiny-tools
          command:
            - sh
            - -c
            - >
              until nc -z -w 2 $POSTGRES_SVC $POSTGRES_PORT && echo database ok; do
                sleep 2;
              done;
          env:
           - name: POSTGRES_SVC
             value: {{ template "xl-release.fullname" . }}-postgresql
           - name: POSTGRES_PORT
             value: "5432"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ImageRepository }}:{{ .Values.ImageTag }}"
          imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
          ports:
            - name: http
              containerPort: 5516
              protocol: TCP
          volumeMounts:
            - name: reports-dir
              mountPath: /opt/xebialabs/xl-release-server/reports
          {{- if .Values.HealthProbes }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.HealthProbesReadinessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.HealthProbesLivenessTimeout }}
            periodSeconds: {{ .Values.HealthPeriodScans }}
            failureThreshold: {{ .Values.HealthProbeFailureThreshold }}
          {{- end }}
          env:
            - name: ADMIN_PASSWORD
              value: {{$XLR_ADMIN_PASS}}
            - name: XL_CLUSTER_MODE
              value: full
            - name: XL_DB_URL
              {{- if not .Values.UseExistingDB.Enabled }}
              value: jdbc:postgresql://{{ template "xl-release.fullname" . }}-postgresql:5432/xlr-db
              {{- else }}
              value: {{ .Values.UseExistingDB.XLR_DB_URL }}
              {{- end }}
            - name: XL_DB_USERNAME
              value: {{$XLR_DB_USER}}
            - name: XL_DB_PASSWORD
              value: "{{$XLR_DB_PASS}}"
            - name: SERVER_URL
              value: "http://localhost:5516"
            - name: XL_LICENSE
              value: {{ .Values.xlrLicense }}
            - name: XL_REPORT_DB_URL
              {{- if not .Values.UseExistingDB.Enabled }}
              value: jdbc:postgresql://{{ template "xl-release.fullname" . }}-postgresql:5432/xlr-report-db
              {{- else }}
              value: {{ .Values.UseExistingDB.XLR_REPORT_DB_URL }}
              {{- end }}
            - name: XL_REPORT_DB_USERNAME
              value: {{$XLR_REPORT_DB_USER}}
            - name: XL_REPORT_DB_PASSWORD
              value: "{{$XLR_REPORT_DB_PASS}}"
            - name: XL_METRICS_ENABLED
              value: "false"
            - name: FORCE_UPGRADE
              value: "true"
            - name: ENABLE_EMBEDDED_QUEUE
              value: "{{$ENABLE_EMBEDDED_QUEUE}}"
            - name: XLR_TASK_QUEUE_USERNAME
              value: "{{$XLR_TASK_QUEUE_USERNAME}}"
            - name: XLR_TASK_QUEUE_PASSWORD
              value: "{{$XLR_TASK_QUEUE_PASSWORD}}"
            - name: XLR_TASK_QUEUE_URL
              value: "{{$XLR_TASK_QUEUE_URL}}"
            - name: XLR_TASK_QUEUE_NAME
              value: "{{$XLR_TASK_QUEUE_NAME}}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: reports-dir
          persistentVolumeClaim:
            claimName: {{ template "xl-release.fullname" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
